version: '3'
services:
    angular-nginx-app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./templates:/etc/nginx/templates
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
